on:
  push:
    branches: [main]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
      - id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
      - if: steps.check.outputs.changed == 'true'
        run: |
          npm install
          npm publish
          npm run typedoc:generate
          git config user.name $REPO_OWNER
          git add -f docs
          git commit --amend --allow-empty-message -m '' --reset-author
          git push origin `git subtree split --prefix docs $BASE_BRANCH_NAME`:$TARGET_BRANCH_NAME --force ||  git subtree push --prefix docs origin $TARGET_BRANCH_NAME
        env:
          TARGET_BRANCH_NAME: gh-pages
          BASE_BRANCH_NAME: ${{ github.head_ref }}
          REPO_OWNER: ${{ github.event.repository.owner.name }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - if: steps.check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.version }}
